# Generated by Django 3.2.10 on 2022-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_uservideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='user_video',
            field=models.FileField(default='/', upload_to='Video'),
        ),
    ]
